[project]
name = 'educational-research-collaboration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-privacy-manager]
path = 'contracts/data-privacy-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-coordinator]
path = 'contracts/project-coordinator.clar'
clarity_version = 2
epoch = 2.5

[contracts.publication-manager]
path = 'contracts/publication-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-collaboration]
path = 'contracts/research-collaboration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
